### ISSUE TITLE
[Feature Request]: Add an "All Corporations" to available corporations

### ISSUE THREAD

**Issue by aaronmallen** [herpaderpaldent/seat-groups#10]
I would like to be able to set a default role (i.e. `Capsuleer`) that would be applied to any user that joined the server regardless of corporate affiliation.  This would be useful in allowing user's that join the server to view Seat Groups and apply for those they are eligible for.

**Comment by herpaderpaldent** [comment]
Would you elaborate your usecase? Why do you think this is needed and why others then you profit from this? Currently i fail to see why you would want to handout roles to _anyone_ joining your SeAT Installation

**Comment by aaronmallen** [comment]
When I a new user logs in I would like a `capsuleer` role to be applied to the user with the `SeatGroups.view` permission.  The `capsuleer` would than be able to apply to join managed or opt-in groups (i.e. `Friend`) that I could then utilize to grant the user a discord role I would grant to out of alliance toons.

**Comment by herpaderpaldent** [comment]
Ok i see the usecase and will take this on my backlog.

**Comment by herpaderpaldent** [comment]
v0.9.5 has just been released
![image](https://user-images.githubusercontent.com/6583519/41821518-2ea2e4f6-77e2-11e8-9a29-1b16566478fe.png)
