### ISSUE TITLE
Feature request: Auto groups based on any linked character

### ISSUE THREAD

**Issue by kwazulueve** [herpaderpaldent/seat-groups#11]
Currently the auto-grouping based on membership of a corporation is (only) looking at the corporation of the main character of a user group.

It would be a useful feature for our corp/alliance to be able to base this on any owned character a user has linked in his group. For example, this way we can easily see the number of users that have a character in a specific alt corporation and assign a role based on that. (Won't bother with the details but we require such an alt, hence the FR).

Thank you for this nice SeAT plugin!

**Comment by herpaderpaldent** [comment]
Hey

Glad you like the plugin. I was always thinking that SeAT is missing it so i went for it. Being originally a wormholer i build the Plugin to be stable against purged members which might have still an alt in given corporation. 
If SeAT Group would accep any linken Character purging might not fully go through cause an alt might still give access to the toll. (imagine the damage what an old director could do ...)

Other then that i am not sure if SeAT Group is the right place for member tracking? Knowing how many spies you got in another Corp isnt particular in scope for this plugin. 
However: if you explain it a little more i might be in asstiance to extend core i.e. Member tracking. 
Maybe i am just missing something?

Yours Herp

PS: Donations are always welcome 😊

**Comment by aaronmallen** [comment]
It would also be pretty dope if you could allow access to a SeAT group based on other SeAT group access... example use case:

I have an `auto` SeatGroup `Capsuleers` with `All Corporations` affiliation which grants a role `Capsuleer` which allows the viewing of SeAT groups. I then have a `managed` SeatGroup `Friends` with an `All Corporation` affiliation.  A user then applies for the "Friends" group and is approved.  I then have two `open` SeatGroups `Politics` and `Memes` (these essentially just grant access to some discord channels) it would be dope if I could make those two `open` SeatGroups accessable by anyone in the `Friends` SeatGroup.

**Comment by herpaderpaldent** [comment]
@aaronmallen i think your idea would qualify for its own feature request. 

@kwazulueve: i still need your feedback on Member tracking

**Comment by kwazulueve** [comment]
Example one: (Industry/hauling/alliance holding) alt corp where a various number of people have alt's in. All those people are eligable to view corp assets etcetera or anything else in SeAT. Autogrouping based on all characters enables that. 

Anyone joining the alt corp could get assigned a SeAT role (with access for that corp) automatically, and subsequently could get access to that specific alt corp in SeAT.

Example two: An alliance requires people to have an Alpha character alt in a specific corp. Automatically assigning a specific SeAT role for being in the main corp and that alt corp gives me an immediate overview of which Users either comply or not to that requirement. 

I am pretty sure there are more Use cases where this would be useful but these two are the ones currently applying for us.

Regarding the Director remark, these things do not depend on giving SeAT roles. If anything you want SeAT (core) help people notice that mains have left but some alts haven't (IE a notification type for that would be useful) but it really does not have anything to do with this issue.
