### ISSUE TITLE
One user not being auto-assigned roles

### ISSUE THREAD

**Issue by AlienXAXS** [herpaderpaldent/seat-groups#116]
Hi,
I am having a strange issue with one user, where they are not being assigned a role even though he is part of the corp and other users are getting those roles.

Within the role itself, I have an affiliation set to the corp:
![image](https://user-images.githubusercontent.com/1773445/59983076-19a06d80-9613-11e9-9b09-f1aa5d85cf17.png)

His character sheet clearly shows that the character is in corp:
![image](https://user-images.githubusercontent.com/1773445/59983091-3d63b380-9613-11e9-853e-ffc6f5642f4b.png)

Impersonating the user shows they have a main character set (in this case, it's their only character they have)
![image](https://user-images.githubusercontent.com/1773445/59983102-566c6480-9613-11e9-8bb1-891c81d3b8ad.png)

Running php artisan seat-groups:users:update does not seem to add this user to the role, however if i add the user to the role manually and run the artisan command, the user gets removed from the role.
![image](https://user-images.githubusercontent.com/1773445/59983117-8b78b700-9613-11e9-9df6-13bad0ef22e8.png)

I assume seat-groups does not think that this user is in corp, thus not adding them?

Any help would be grand,
Thanks

**Comment by Meganitrospeed** [comment]
having a similar issue but reverse

**Comment by herpaderpaldent** [comment]
honestly: seat core devs kinda bullied me out of the project and banned me from slack. 

Maybe ask someone in the slack to help you out, mostly it has something to do with either no refresh-token present, no character_info was pulled from esi or cache been compromised.
