### ISSUE TITLE
Is the about page intended to be linked to the Seatgroups.view permission?

### ISSUE THREAD

**Issue by ghost** [herpaderpaldent/seat-groups#119]
Seatgroups.view is the only way for end users to view the groups, such as open or managed. It seems unusual that the about page, which shows things such as the bug report link and update history, to be visible with this permission. Calling attention to this because I'm not sure if this was the intended affect, or if it's a bug

**Comment by herpaderpaldent** [comment]
This is done by design as bugs could be found by regular users as well. The history however is scoped and only available with seatgroup.create permission
