### ISSUE TITLE
[Feature Request]: SeAT group affiliations

### ISSUE THREAD

**Issue by aaronmallen** [herpaderpaldent/seat-groups#12]
Allow access to a SeAT group based on other SeAT group access... example use case:

I have an auto SeatGroup Capsuleers with All Corporations affiliation which grants a role `Capsuleer` which allows the viewing of SeAT groups. I then have a managed SeatGroup `Friends` with an All Corporation affiliation. A user then applies for the `Friends` group and is approved. I then have two open SeatGroups `Politics` and `Memes` (these essentially just grant access to some discord channels) it would be dope if I could make those two open SeatGroups accessable by anyone in the `Friends` SeatGroup.

**Comment by mmolitor87** [comment]
This is similar to how I requested being able to get a group as seat-group managers.  Such as, anyone in the directors group can approve/deny a particular managed group request.

**Comment by herpaderpaldent** [comment]
I like this request, i think this is duable. Although @mmolitor87 i don't think this will solve your request on automatically assign managers to a SeAT-Group. It would only allow Users in the Friends Group to see, opt-in and apply for other SeAT Groups

**Comment by mmolitor87** [comment]
Using groups for things is still a step closer. Just need to make the groups available as managers. :)

**Comment by herpaderpaldent** [comment]
Big news: SeAT-Groups will become an integrated part in the next major [SeAT Release](https://github.com/eveseat/seat/issues/394) (currently named SeAT 3.1) 

By doing this i must make sure that anything i program is compatible with SeAT Core. When i thought about this Feature Request i thought about using self-referencial relationship. This is different from f.e. the n:m relationship from `seat_groups` to `corporations` (many-to-many). I need to align with qu1ckkk over this feature. Maybe there is a better approach to this challenge. 

I still plan on this feature, however i wanted to let you know why the feature is delayed

**Comment by herpaderpaldent** [comment]
solved with: https://github.com/herpaderpaldent/seat-groups/releases/tag/1.3.0
