### ISSUE TITLE
Update for SeAT 4.x planned?

### ISSUE THREAD

**Issue by ppfeufer** [herpaderpaldent/seat-groups#121]
SeAT 4.x is coming, any update planned?

**Comment by herpaderpaldent** [comment]
Hey @ppfeufer 
Thank you for letting me know, i was not aware of a version 4.x. I am surprised that my plugin would still be needed as the maintainers qu1ckkk @leonjza wanted to make this a native functionality with SeAT 3.1.

If someone submits a PR which passes the tests i'll merge it.

**Comment by herpaderpaldent** [comment]
Seems @warlof covers it with squads in 4.x
