### ISSUE TITLE
Large Event Log

### ISSUE THREAD

**Issue by matsfinsas** [herpaderpaldent/seat-groups#122]
Event log currently has 4000 pages on my installation.
What's the easiest way to clean out old logs, alternatively is there a function in the app to regularly clear logs older than X days?

**Comment by herpaderpaldent** [comment]
So there is a big fat button `clear` you can hit to delete the entire log.

![image](https://user-images.githubusercontent.com/6583519/69325197-0d641f00-0c4a-11ea-9d13-072dec80166b.png)

I would definitively not reimplement the log like this again. With LazyCollections available in Laravel 6 i would do rotating log files. I handle this as *won't fix* in this issue and  i would suggest you asking @warlof and the other's for seat 3.1 and above to not copy the DB-Log function when they include seat-groups into core.
