### ISSUE TITLE
SeATGroups fails to assign groups

### ISSUE THREAD

**Issue by autophob** [herpaderpaldent/seat-groups#123]
On my server SeATGroups fails to assign groups, apparently because a character has no main_char set up. however, I double- and triple-checked all of them and they all have a main.

Here's the log:

> Error
> Herpaderpaldent\Seat\SeatGroups\Exceptions\MissingMainCharacterException: The group with ID 1 does not have a main character set, or related character information is missing. in /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/herpaderpaldent/seat-groups/src/Actions/Seat/GetMainCharacterAction.php:22
> Stack trace:
> #0 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupSync.php(67): Herpaderpaldent\Seat\SeatGroups\Actions\Seat\GetMainCharacterAction->execute(Object(Seat\Web\Models\Group))
> #1 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupDispatcher.php(32): Herpaderpaldent\Seat\SeatGroups\Jobs\GroupSync->__construct(Object(Seat\Web\Models\Group))
> #2 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher->Herpaderpaldent\Seat\SeatGroups\Jobs\{closure}(Object(Seat\Web\Models\Group), 0)
> #3 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupDispatcher.php(35): Illuminate\Support\Collection->each(Object(Closure))
> #4 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiter.php(75): Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher->Herpaderpaldent\Seat\SeatGroups\Jobs\{closure}()
> #5 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiterBuilder.php(113): Illuminate\Redis\Limiters\ConcurrencyLimiter->block(3, Object(Closure))
> #6 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupDispatcher.php(42): Illuminate\Redis\Limiters\ConcurrencyLimiterBuilder->then(Object(Closure), Object(Closure))
> #7 [internal function]: Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher->handle()
> #8 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #9 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #10 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
> #11 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
> #12 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
> #13 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher))
> #14 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher))
> #15 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #16 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher), false)
> #17 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
> #18 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
> #19 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
> #20 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
> #21 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\Queue\WorkerOptions))
> #22 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high,medium,low...')
> #23 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
> #24 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
> #25 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #26 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #27 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
> #28 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
> #29 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
> #30 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #31 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #32 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/symfony/console/Application.php(982): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #33 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #34 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #35 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #36 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #37 /var/www/vhosts/jesco.industries/seat.jesco.industries/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #38 {main}
> Data
> {
>   "tags": [
>     "dispatcher"
>   ],
>   "tries": 1,
>   "job": null,
>   "connection": null,
>   "queue": "high",
>   "chainConnection": null,
>   "chainQueue": null,
>   "delay": null,
>   "chained": []
> }

**Comment by herpaderpaldent** [comment]
Looks like a duplication of https://github.com/herpaderpaldent/seat-groups/issues/117
