### ISSUE TITLE
Warning spam in event logs

### ISSUE THREAD

**Issue by yarmout** [herpaderpaldent/seat-groups#124]
When a user removes their ESI Token from a SeAT Installation (Such as when moving to a new corp), SeAT groups gives a warning that they may lose their roles. The problem is that it displays this same warning every single hour, for each character that had it's ESI Token removed, clogging up the event log quite a bit. Due to this, other events get buried underneath these warnings. Perhaps this warning should only be displayed the first time it notices that the ESI tokens are missing, that way the SeAT admin is still notified, but without spamming the events log.

**Comment by herpaderpaldent** [comment]
You can stop this warning by deactivating the user. This solution has been promoted in the changelog
