### ISSUE TITLE
Alliance doesn't trickle into Seat group properly

### ISSUE THREAD

**Issue by DM1985** [herpaderpaldent/seat-groups#127]
Having an issue with seat group, in the alliance filter i can see my alt alliance but not the one i need to asign role to. 

But when you look at the character registered, you can actually see the proper alliance. 

Just can't select it from the Seat Group drop down list.

I have looked into the Seat data base and can find the alliance there.

Any informations i can send to help resolve the issue.

Thank you in advance!

**Comment by herpaderpaldent** [comment]
I saw at somepoint warlof pushing some changes to character_affiliations and character_info which ultimately broke seat-groups, i don't think i am going to fix this. 
potentially you could create the DB entry manually to get it working

**Comment by warlof** [comment]
@herpaderpaldent there are no change made to either `character_affiliations` or `character_infos` in the version you're supporting.

**Comment by herpaderpaldent** [comment]
🤷‍♂️ i don't follow seat anymore, i just saw some commits regarding the cached character_info endpoint.  Good to know it did not impact current seat version. Then i would not know what the issue could be

**Comment by warlof** [comment]
just in case, he fixed his issue by removing an existing coupling with a corp.
Seems you don't allow cross type coupling (alliance and corp in this case).

**Comment by herpaderpaldent** [comment]
I checked and you are correct it's because i don't allow affiliations for alliances for which a corporation affiliation is already setup. It makes kinda sense. Why having a corp affiliation if you have an alliance affiliation which includes the corp anyway.
