### ISSUE TITLE
[Feature Request]: Group application notification

### ISSUE THREAD

**Issue by aaronmallen** [herpaderpaldent/seat-groups#13]
It would be pretty useful for managers of a group to receive notifications of pending applications in their respective seatgroups.

**Comment by herpaderpaldent** [comment]
Notifications from a package certainly doable however a bit more complex. However, this plugin is scheduled to be integrated in core SeAT with 3.1. With that version latest notifications are going to be a thing,
Depending on other work i have currenty on the notificiation package this FR might be solved earlier then 3.1.

**Comment by herpaderpaldent** [comment]
This is now available with version `1.6.8`

https://github.com/herpaderpaldent/seat-groups/releases/tag/1.6.8 

thank you for your idea and your patience
