### ISSUE TITLE
unable to verify killmail for SRP

### ISSUE THREAD

**Issue by Simcity1976** [herpaderpaldent/seat-groups#130]
https://esi.evetech.net/v1/killmails/86892227/3044107a1de8726b928e733b739cdc7c3196159e/?datasource=tranquility

this comes up as invalid killmail when trying to enter it SEAT

**Comment by herpaderpaldent** [comment]
Wrong seat plugin. 
 
Maybe bump this issue as it might be related: https://github.com/dysath/seat-srp/issues/40
