### ISSUE TITLE
seat-groups does not work with 4 version

### ISSUE THREAD

**Issue by elrond1975** [herpaderpaldent/seat-groups#131]
Hi.

 composer require herpaderpaldent/seat-groups
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.7 for herpaderpaldent/seat-groups
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for herpaderpaldent/seat-groups ^1.7 -> satisfiable by herpaderpaldent/seat-groups[1.7.0, 1.7.1, 1.7.2].
    - Can only install one of: eveseat/web[4.2.2, 3.0.x-dev].
    - Can only install one of: eveseat/web[3.0.x-dev, 4.2.2].
    - Can only install one of: eveseat/web[3.0.x-dev, 4.2.2].
    - Conclusion: install eveseat/web 3.0.x-dev
    - Installation request for eveseat/web (locked at 4.2.2, required as ^4.0) -> satisfiable by eveseat/web[4.2.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by herpaderpaldent** [comment]
Yes this is correct. Seat v4 has implemented something that should replace groups. I receive mixed feedback about its quality but this out of my hands.

My corp is not chaning to v4 as it is known to nuke your refresh tokens and v3 is announced to be supported until end of year.

**Comment by elrond1975** [comment]
ty
