### ISSUE TITLE
[Feature Request]: Auto group based on skills/assets

### ISSUE THREAD

**Issue by Ycer0n** [herpaderpaldent/seat-groups#14]
It would be cool if you could make a group and people would automatically get added based on wether they have a ship and the right skills
For example: Super group
People would automatically get added to the group if they own a super, have racial carrier skill to 4 and jump drive calibration 5. An even better enhancement would be if you could also choose the location the ship has to be in so you can make a group just for deployed super pilots and leave ratting supers out.

Another small suggestion I have is adding the available for corporation for alliances as well.
So if a corp leaves the alliance, all their members will get removed from the group and the corp doesn't have to be removed from the access list.

Lastly, another suggestion would be to invert a permission like you can with the normal groups on seat
use: A role for recruits, everyone who is not in a certain corp/alliance gets added to the recruit group

**Comment by herpaderpaldent** [comment]
Due to inactivity of request owner, i close this issue. Feel free to reopen it, whenever it suits you.
