### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marazmatik** [herpaderpaldent/seat-groups#16]
[2018-08-25 20:12:18] local.ERROR: Trying to get property of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property of non-object at /var/www/seat/vendor/herpaderpaldent/seat-groups/src/Commands/SeatGroupsUserUpdate.php:40)
Version 1.0.0

**Comment by herpaderpaldent** [comment]
Need more info on this. What do you try to do prior to this error?

**Comment by marazmatik** [comment]
i am making   
php artisan  seat-groups:users:update

and, have such error

In SeatGroupsUserUpdate.php line 40:
                                    
  Trying to get property of non-object

**Comment by herpaderpaldent** [comment]
Yes as @flyingferret suggests make sure every user has a main-character set. This should be the case for any user created after Seat 3.0 (production). User created in beta might lacking of such main_character and this might be your case. 
I am going to close the issue. Feel free to reopen it, if the problem persist.
