### ISSUE TITLE
Log entry: exception GroupSync.php

### ISSUE THREAD

**Issue by kwazulueve** [herpaderpaldent/seat-groups#23]
[2018-09-12 09:15:16] local.ERROR:  {"exception":"[object] (Herpaderpaldent\\Seat\\SeatGroups\\Exceptions\\MissingRefreshTokenException(code: 0):  at /var/www/seat.tgrad.space/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupSync.php:129)
[stacktrace]
#0 /var/www/seat.tgrad.space/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupSync.php(52): Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync->beforeStart()
#1 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiter.php(75): Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync->Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\{closure}()
#2 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Redis/Limiters/ConcurrencyLimiterBuilder.php(113): Illuminate\\Redis\\Limiters\\ConcurrencyLimiter->block(3, Object(Closure))
#3 /var/www/seat.tgrad.space/vendor/herpaderpaldent/seat-groups/src/Jobs/GroupSync.php(106): Illuminate\\Redis\\Limiters\\ConcurrencyLimiterBuilder->then(Object(Closure), Object(Closure))
#4 [internal function]: Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync->handle()
#5 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#10 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync))
#11 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync))
#12 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Herpaderpaldent\\Seat\\SeatGroups\\Jobs\\GroupSync), false)
#14 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#15 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#16 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#17 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#18 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('redis', 'high,medium,low...', Object(Illuminate\\Queue\\WorkerOptions))
#19 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'high,medium,low...')
#20 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#21 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#22 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#26 /var/www/seat.tgrad.space/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#27 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/seat.tgrad.space/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /var/www/seat.tgrad.space/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/seat.tgrad.space/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/seat.tgrad.space/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/seat.tgrad.space/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 {main}
"}

**Comment by herpaderpaldent** [comment]
This works as intended. One of the user_groups RefreshToken is invalid therefore user_group loses all roles.
