### ISSUE TITLE
Log Entry: Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher

### ISSUE THREAD

**Issue by odious** [herpaderpaldent/seat-groups#28]
Hey there, i just installed seat-groups, added one group and got this message in the logs:

seat-worker    | 2018-09-19T10:45:55.002272370Z [2018-09-19 10:45:54] Processing: Herpaderpaldent\Seat\SeatGroups\Jobs\GroupDispatcher
seat-worker    | 2018-09-19T10:45:55.002292923Z
seat-worker    | 2018-09-19T10:45:55.002310087Z In CallQueuedHandler.php line 148:
seat-worker    | 2018-09-19T10:45:55.002326950Z
seat-worker    | 2018-09-19T10:45:55.002343791Z   method_exists(): The script tried to execute a 
method or access a property
seat-worker    | 2018-09-19T10:45:55.002360703Z   of an incomplete object. Please ensure that the class definition "Herpaderp
seat-worker    | 2018-09-19T10:45:55.002377300Z   aldent\Seat\SeatGroups\Jobs\GroupDispatcher" of the object you are trying t
seat-worker    | 2018-09-19T10:45:55.002393904Z   o operate on was loaded _before_ unserialize() gets called or provide a __a
seat-worker    | 2018-09-19T10:45:55.002410417Z   utoload() function to load the class definition
seat-worker    | 2018-09-19T10:45:55.002428271Z
seat-worker    | 2018-09-19T10:45:55.002447889Z

**Comment by herpaderpaldent** [comment]
Hey @odious,
Thank you for this report. I have never seen this before and based on the feedback inside that log i suspect that Sync-Job and your adding of the group just hit at the same time.  `he script tried to execute a method or access a property of an incomplete object.`

Please let me know if this error persist.

**Comment by herpaderpaldent** [comment]
I close this issue, due to inactivity of OP. Feel free to reopen it if you have to add something to it.
