### ISSUE TITLE
Request - Discord intergration

### ISSUE THREAD

**Issue by KongGal** [herpaderpaldent/seat-groups#3]
Hello! Would it be possible to maybe have discord intergration in over this plugin?
or maybe a seat-discord that could interact with seat-groups
from seat you can click on discord and you can get a server invite from there and a member role is granted.
and then seat-discord would read seat-groups to add/remove other groups?

**Comment by KongGal** [comment]
Nice to hear  
got access to slack after i had asked and saw his startup of the discord connector but lets hope he would support Seat-Groups

**Comment by herpaderpaldent** [comment]
I am going to close this issue out of following reasons: 
1. Warlof will not support channel Mgmt with Discord integration. At least not at the moment
2. If ever supported it will respect roles
3. SeAT-Group is build agnostic and may have bound multiple roles. To work with slackbot or discordbot you may create an empty role f.e. Directors with no affiliation or permissions and assign the SeAT-Group to the empty director role. (NOTE: the role must not be empty)
