### ISSUE TITLE
Not all corp members assigned generic corp member group

### ISSUE THREAD

**Issue by geedon** [herpaderpaldent/seat-groups#31]
Hi, first of all thanks for creating this plugin. [Warlof told me](https://github.com/warlof/seat-discord-connector/issues/23) that this plugin is required to ensure I can continue to use the discord connector plugin since a recent update of eveseat to v3.0.8.

I'm trying to get all members of my corporation to be added to a group called 'corp members' automatically. It works for the most part, but not everyone is getting assigned to this group some are, some aren't and I'm not sure why. Here's a picture of what I have in my seat-group settings...

![image](https://user-images.githubusercontent.com/17879075/46260573-acc2d180-c4df-11e8-8322-73f30fb46afc.png)

I don't appear to get any errors. I don't suppose you could help with this could you?

**Comment by herpaderpaldent** [comment]
Hey @geedon, 
Thank you for reaching out. Have you checked the log entries for SeAT-Group on the about page? There should be an event-log (with a result) per User-group.  This should look like this:
![image](https://user-images.githubusercontent.com/6583519/46260660-32974a80-c4e9-11e8-84d0-91775f286d09.png)

Does this help you solve your issues?

**Comment by geedon** [comment]
Hi and thanks for the quick response! I see no entries for the people in question, who I would expect this missing group associated. I do see a couple of repeated warnings for missing refresh tokens but these are valid as the members just left corp.

BTW I am on version 1.3.4 same as your screenshot

Thanks again!

**Comment by herpaderpaldent** [comment]
Hey,

there are two things you could try: 
1. enable debug and try to manually sync the character in question with `php artisan seat-groups:users:update --character_ids=ID`. Then you might forward me the logging results from this job.
2. Join seat-slack and i might be of assistance more directly then via github ticket: https://eveseat-slack.herokuapp.com/

**Comment by geedon** [comment]
Hi, interestingly when I ran the command manually... 

`php artisan seat-groups:users:update --character_ids=2112534214`

He got his group, but there were previously no errors or success entries for this guy when it ran automatically via the scheduled tasks. Even when I Manually executed the schedule with ...

`php artisan seat-groups:users:update `

..there were no entries in the log

My corp is quite large 200+ and I've had issues in the past with other plugins related to this. Might there be some limitations?

Thanks again for your time!

**Comment by herpaderpaldent** [comment]
Did you restart supervisor or the `seat-worker` container if you use docker after installing version 1.3.4? 

thanks to @warlof we improved the group dispatcher in the latest update and without restarting either of those two the workers might still have old code loaded.

**Comment by geedon** [comment]
Thanks for the extra info. But some peeps have main chars and still are missing the default group...

![image](https://user-images.githubusercontent.com/17879075/46295287-91af9a80-c58f-11e8-9b3c-7d05c19d132b.png)

But I see entries in the logs from just a few minutes ago...

- The user group of Treava Crendraven (Treava Crendraven) has successfully been synced.
- The user group of Saeko Vodkarage (Saeko Vodkarage) has successfully been synced.
- The user group of grisee whenne (grisee whenne) has successfully been synced.

Not entirely sure what you mean by this comment...

"This and running old (prior 1.3.4) SyncGroup job in the workers has caused 100% your issues."

Can I assume, as I'm running Version 1.3.5, that this isn't an issue? or do I need to do some kind of artisan update? I'm a little new to this framework TBH.

'

**Comment by herpaderpaldent** [comment]
Best if you hop on to slack and we can further discuss: https://eveseat-slack.herokuapp.com/

**Comment by herpaderpaldent** [comment]
As it turned out, the package was working within parameters. The named users were not qualified for the user-group as they were still in a NPC corporation. 

I take this support issue to slack and close this issue as it is no technical defect.
