### ISSUE TITLE
[Feature Request] QOL Accept multiple group applications

### ISSUE THREAD

**Issue by 0wnedadmin** [herpaderpaldent/seat-groups#35]
Id like the ability to accept multiple applicants to a seat group without having to open the manage members window for each person I accept.

Simple QOL request, nothing major.

<3

**Comment by herpaderpaldent** [comment]
Will be there with the next release

**Comment by herpaderpaldent** [comment]
just that you know, it wasn't so simple .... it took me a couple of hrs to figure that one out. Generally in IT there is no such thing as simple requests
