### ISSUE TITLE
Wrong view permissions on hidden groups

### ISSUE THREAD

**Issue by jediefe** [herpaderpaldent/seat-groups#38]
Users can see all hidden groups where their affiliation matches with the ones defined in the group. Expected behaviour would be that they only see hidden groups they are member of. 
The Screenshot shows a C2CF member view of hidden groups that have the C2CF affiliation defined, but the user is not a member of any of these groups. 

![grafik](https://user-images.githubusercontent.com/1344247/46825917-00ada000-cd95-11e8-91a7-4d9eec208704.png)

**Comment by herpaderpaldent** [comment]
Gonna be adressed in next patch
