### ISSUE TITLE
Alliance filter is showing wrong list

### ISSUE THREAD

**Issue by warlof** [herpaderpaldent/seat-groups#39]
Thanks for the alliance filter addition in last update.

It seems the wrong list has been displayed in the tab though as I get the corporation list instead the alliance one.

**Comment by herpaderpaldent** [comment]
That is odd ... Did you try it with a fresh group? Alliance is filtered if you got a corp or corp title affiliation of an alliance member

**Comment by dougestey** [comment]
For me I see the alliances correctly, but the button/UI still refers to them as "corporations"

**Comment by herpaderpaldent** [comment]
Yep @dougestey good catch ... need to improve this one

**Comment by herpaderpaldent** [comment]
i added some translations and now the button refers to alliance
