### ISSUE TITLE
[Suggestion] Notification icon when someone applied to a group

### ISSUE THREAD

**Issue by Busterguy** [herpaderpaldent/seat-groups#41]
Little suggestion for ease of life.

If possible on the managed groups page where people apply to groups.
Add a little notification icon above the group if it has pending applications for the person who can approve/reject them

Kinda like this:
http://prntscr.com/l8bx4g

Sorry for bad paint

**Comment by herpaderpaldent** [comment]
I reject this request because of bad paint. 

But i gladly accept the feature request 😊 because it would be a great addition

**Comment by herpaderpaldent** [comment]
Implemented with Version 1.4.2
![image](https://user-images.githubusercontent.com/6583519/47260457-25ec8d80-d4bc-11e8-9272-8f9ee5ebc96a.png)
