### ISSUE TITLE
Submitting Blank "Available Corporation" in Corporation Filter Causes Server Error

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#55]
**Summary**
Inadvertently omitting to choose a corporation in the "Corporation Filter" when creating a SeAT group causes an `Internal Server Error`.

**Discussion**
Looks like the input for the "Corporation Filter" in "Available for Whom" doesn't sanity check for missing input and then tries to do something with that missing input. Oops!

At least it should be a simple fix. (-:

**Comment by herpaderpaldent** [comment]
You are absolutely right:
https://github.com/herpaderpaldent/seat-groups/blob/master/src/Http/Validation/Affiliation/AddCorporationAffiliationRequest.php#L35

The validation must have been turned off by me during development of `corporation_titles` affiliation and i must have forgotten to uncomment it again. Next release will include this again
