### ISSUE TITLE
Only First User Group Is Added Using Hidden Group's "Add User"

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#56]
**Summary**
When editing a `Hidden SeAT Group`, only the first of the list of selected users is added when `Add User` is pressed.

**Discussion**
The `Hidden SeAT Group` user configuration block allows you to pick multiple users ("groups") from those available. When clicking "Add User", only the first is added. Granted the button says "Add User" and not "Add Users", but other similar configuration areas, like choosing SeAT groups for adding managers, work fine with multiple selections.

**Comment by herpaderpaldent** [comment]
Thank you for reporting. Will be solved in next release
