### ISSUE TITLE
Minor Broken UI

### ISSUE THREAD

**Issue by GoemFunaila** [herpaderpaldent/seat-groups#66]
<img width="319" alt="20190110_210455" src="https://user-images.githubusercontent.com/44015503/50967501-a9e26e80-151b-11e9-8f74-e9dbdea15e53.png">
'Search: (textbox)' is broken

**Comment by herpaderpaldent** [comment]
can you specify broken? You mean it doesn't work or just that it overflows? 

Have you tried if the UI appears like this in every browser and different browsersizes?

**Comment by herpaderpaldent** [comment]
Closing this issue due to OP inactivity
