### ISSUE TITLE
Group dont work for me

### ISSUE THREAD

**Issue by Dracks977** [herpaderpaldent/seat-groups#7]
Kick members of legacy seat group and dont add members to that group (work with old groupe created with webseat beta 20)

**Comment by herpaderpaldent** [comment]
After discussion with creator of this issue:

It was a configuration error by the user. For any SeAT-Group you need to assign valid corporations to the SeAT-Group. This is a feature to prevent users still carring roles that might have been purged from corporation. However this is not the first issue with this feature i leave this ticket open as an improvement request. I need to explain this better.
If any one got a suggestion

**Comment by herpaderpaldent** [comment]
This issue has been adressed with the latest version: 
![image](https://user-images.githubusercontent.com/6583519/41510101-c76aa41e-725e-11e8-9c09-fb9700ca5b29.png)
