### ISSUE TITLE
[Enhancement] Display groups alphabetically on SeAT Groups Dashboard

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#78]
**Summary**
Display groups in alphabetical order by name on the SeAT Groups Dashboard in the different categories.

**Related**

**Discussion**
When you have a zillion groups, it can be difficult for users or managers to quickly find the desired group on the Dashboard because they're listed in the order they were created rather than in a way people can predict. It would be nice if they were sorted alphabetically by name. That would help a lot. A dynamic filter based on user-input in a text-field would work too, but that feature would be even more awesome in conjunction with alphabetical listing.

**Implementation**
Implementing alphabetical listing is likely only a matter of adding an appropriate `ORDER BY` clause to the existing queries that retrieve the groups to display on the relevant SeAT Groups Dashboard tabs or sorting the returned query object results in PHP prior to display. Low-lying fruit either way!

**Comment by herpaderpaldent** [comment]
Could you split the two stories please. Also reading your implementation details i reflected myself and how i am writing stories for my team. 
Its meant well but a couple of bulletpoints would have been enough 😉. 

I gonna collect feedback on the ordering idea asap
