### ISSUE TITLE
Only superusers can see SeAT Groups menu item

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#8]
## Summary
Nobody can see the SeAT Groups menu item, except the superuser, and therefore they can't apply for managed groups.

## Environment
- SeAT 3.0.1 in a Docker image. New installation, not an upgrade.
- SeAT Groups (Jun 17, 2018 commit)
- CentOS 7.5.1804
- Apache/2.4.6 (CentOS) as front end.

## Discussion
At first I thought, "Ah! They probably need permissions to see the groups." I checked and there was a permission for that. It's apparently not assigned to everyone by default. 

"No problem! I'll make a role for it and a SeAT auto-group to have it auto-assigned to everyone."  Good theory, but it doesn't seem to work in practice. I tried creating the auto-group to include all the corporations and assign the SeAT role that only contains ``Seatgroups.view`` permission (which was bound to ``All Corporations``).  Nobody was assigned the role by the auto-group, not immediately, not in a few hours, not by the next day.

If I manually added someone to the permissions role, then they suddenly could see the SeAT Groups menu option. I'm thinking needing to manually give everyone permission isn't working as intended, so I must be doing something wrong.

**Comment by herpaderpaldent** [comment]
Your initial thinking was right. You need `Seatgroups.view` permission to be able to see the SeAT Groups. SeAT Groups is not respecting the Corp-Affiliations of roles, you need instead select in the `Auto` Group the corporation. Not selecting a Corporation (middle coloumn) will not result in receiving any SeAT Group Roles. 

This is how it should look like. Make sure (1) is/are the corporations whos members should get the `Seatgroups.view` Permission:
![image](https://user-images.githubusercontent.com/6583519/41681081-d141cc0c-74d3-11e8-9e59-54076f2ee583.png)

if not after 15min the users are receiving the roles. Make sure you have no 'ghost' user-groups which were created before SeAT Beta 20. If you have any more questions, join slack/plugin channel i am happy to help there. 

This is no Bug/Code error, this is why i close the issue.
