### ISSUE TITLE
BUG: Fatal error from route:list if seat-notifications not installed

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#83]
**Summary**
Fatal error generated when running `artisan route:list` command if `seat-notifications` is not installed due to missing HTTP controller requested by SeatGroupSyncController.

**Version**
SeAT 3.0.14
Observed in SeAT Groups 1.6.8 and 1.6.9

**Error**
> 
> PHP Fatal error:  Class 'Herpaderpaldent\Seat\SeatNotifications\Http\Controllers\BaseNotificationController' not found in /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/Http/Controllers/Notifications/SeatGroupSyncController.php on line 7
>
> In SeatGroupSyncController.php line 7:
>                                                                                                        
>  Class 'Herpaderpaldent\Seat\SeatNotifications\Http\Controllers\BaseNotificationController' not found

**Comment by herpaderpaldent** [comment]
Nothing wrong with that error. Yes this happens due to inter compatibility between to other packages. Then again who uses `artisan route:list`.

Won't fix at the moment.
