### ISSUE TITLE
Error: Trying to get property of non-object in hidden-group.blade.php

### ISSUE THREAD

**Issue by Eingang** [herpaderpaldent/seat-groups#84]
**Summary**
Rendering SeAT Groups dashboard generates server error because `hidden-group.blade.php` is trying to access a property of a non-object.

**Version**
SeAT 3.0.14
SeAT Groups 1.6.9

**Error**
> [2019-02-15 16:49:05] local.ERROR: Trying to get property 'name' of non-object (View: /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/resources/views/partials/hidden-group.blade.php) (View: /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/resources/views/partials/hidden-group.blade.php) {"userId":92355251,"email":"ein@somewhere.com","exception":"[object] (ErrorException(code: 0): Trying to get property 'name' of non-object (View: /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/resources/views/partials/hidden-group.blade.php) (View: /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/resources/views/partials/hidden-group.blade.php) at /home/sites/bladesofgrass.space/seat/seat/storage/framework/views/01e9a292ca7186f041f10335bd6e6ca67e90c972.php:9, ErrorException(code: 0): Trying to get property 'name' of non-object (View: /home/sites/bladesofgrass.space/seat/seat/vendor/herpaderpaldent/seat-groups/src/resources/views/partials/hidden-group.blade.php) at /home/sites/bladesofgrass.space/seat/seat/storage/framework/views/01e9a292ca7186f041f10335bd6e6ca67e90c972.php:9, ErrorException(code: 0): Trying to get property 'name' of non-object at /home/sites/bladesofgrass.space/seat/seat/storage/framework/views/01e9a292ca7186f041f10335bd6e6ca67e90c972.php:9)
> …snip…

**Discussion**
I was using the web interface to add users to hidden groups over an hour-long period. At some point, I clicked on the menu item to return back to the SeAT Groups dashboard and had a nasty server misconfiguration error. The Laravel log shows SeAT Groups synching without errors at least twice during the hour period I was doing this. 

It wasn't just me who couldn't see the page. Seemingly anyone I tried with `SeatgroupsView` or `SeatgroupsCreate` permissions could no longer view the SeAT Groups dashboard via the menu item. The `About` page works fine. Synching continues without any errors in the Laravel log (with `Debug` enabled).

I'm not a number! I'm a free pilot with a name!

**Comment by herpaderpaldent** [comment]
Seems like user `92355251` does not have a main_character set

**Comment by Eingang** [comment]
Good theory, but that's not it. I'd just spent several hours doing stuff with no problem. However, on the off chance my main character preference had somehow disappeared, I went to my Profile and checked my main preference when the error occurred. I even clicked 'Update' just to be sure. 

![Ein User Listing](https://user-images.githubusercontent.com/1554544/52884912-5640f180-3167-11e9-9e22-c15cdcbfa1db.png)

![Ein Profile](https://user-images.githubusercontent.com/1554544/52884885-3b6e7d00-3167-11e9-887f-1feb82812c6f.png)

The other user groups I tested with also had mains set. There's only one user group currently with no main set.

**Comment by entropylaw** [comment]
I am also having this exact issue. I created new accounts from separate EVE accounts, set them as superuser and they also get this error. How ever, when I impersonate regular users, they can view groups.

**Comment by herpaderpaldent** [comment]
Good chance it relates to https://github.com/herpaderpaldent/seat-groups/issues/115

It makes sense for a superuser to get that error

**Comment by entropylaw** [comment]
It has worked fine for the last year. Just rather randomly started doing it. Also every user that is active, had to go and "set their main character" that was ready set to view the index of seat groups. I gave a toon without super user all seatgroup perms, they can browse it, but they cant see all the groups like my super user account can.
