### ISSUE TITLE
Alliance filter is empty

### ISSUE THREAD

**Issue by JHXSMatthew** [herpaderpaldent/seat-groups#88]
Hi,

I was trying to add a filter to a group so that only ppl in the alliance will be automatically joined.

however, the alliance filter is always empty (no results).

I was wondering if you could help with this.

Regards.

**Comment by herpaderpaldent** [comment]
This seems to be a question for Support. Please join slack plugin channel to contact me with your issue: https://eveseat-slack.herokuapp.com/ 

i'd be guessing but there is a high chance that you need to run public-job update to get Alliance table seeded or may have a browser addblocker that limits affiliation endpoint (although that should be resolved for quite some time)
