### ISSUE TITLE
[Feature Request]: View Members Permission

### ISSUE THREAD

**Issue by aaronmallen** [herpaderpaldent/seat-groups#9]
I'd like to conditionally allow a user to be able to view members of a group.

(i.e. I Given a group called Super Pilots, only users with the role Supers can view members of the group on the groups page)

Perhaps this can be done by adding a new permission like `SeatgroupsViewMembers`

**Comment by aaronmallen** [comment]
In my use case Supers is a `managed` group... however the way I could see this can be group type agnostic.  If you were to implement a permission SeatGroups.viewMemebers and only allow users with this permission to be able to view the member list.

**Comment by herpaderpaldent** [comment]
As i said: permissions are not the was to go here but i could limit the ppl see the memberlist to the one already in the group. Would this help you?

**Comment by herpaderpaldent** [comment]
I implemented this with Version 0.9.5
